# Site settings
title: DS Blog
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Dirk
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://dirkules339.github.io" # the base hostname & protocol for your site
gems: [jekyll-paginate,jekyll-seo-tag,jekyll-sitemap]
paginate: 3
google_analytics: 'UA-XXXXXXX-X'
